### PR TITLE
Shipment dashboard

### PR DESCRIPTION
**Pull request by KilliBruhh**

### CODE REVIEW

**Comment by KilliBruhh** [comment]
Formatted

**Comment by KilliBruhh** [comment]
I am changing a few things, will reopen once it is done

**Comment by KilliBruhh** [comment]
Will be adding changes

**Review by ThomasFrans — CHANGES_REQUESTED** [review]
Incorrectly merged.

**Comment by ThomasFrans** [comment]
I think it's best to not merge this one into main, as it's full of merge errors. It can either go into `other-main` (preferred) or be demonstrated separately. @jentevs @inancalp

**Pull request closed without merging**
