### PR TITLE
Corrections on shipment

### PR DESCRIPTION
**Pull request by biomoz**
corrected the creation page and added extra statuses for delete and decline function

### CODE REVIEW

**Review by ThomasFrans — CHANGES_REQUESTED** [review]
https://github.com/Practice-Enterprise2/AD#pull-request-requirements

**Comment by biomoz** [comment]
In the current app, when you decline or delete a shipment you get an error. Because you have to set the status of the shipment to declined or deleted. But since status is an enumeration, you can't put them because there is no option for it. That's why we have to add declined and deleted to status enumeration. The changes on the create page is done because it doesnt make sense to set status during creation and the text of dates should be black

**Comment by biomoz** [comment]
Created a new migration file for status enum update and reverted the changes on the previous migration file

**Review by ThomasFrans — CHANGES_REQUESTED** [review]
Incorrect migration: the rollback doesn't correctly revert the migration!

**Review by ThomasFrans — APPROVED** [review]

**Pull request merged**
